apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/codefresh-io/cli-v2/tree/main/manifests/argo-workflows?ref=v0.0.69

patches:
  # reset the crbs to `subject.namespace: default`, so that argo-workflows will later change them to the actual ns
  - target:
      kind: Deployment
      name: argo-server
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args
        value: 
          - server
          - --auth-mode
          - server
          - --auth-mode
          - client
